# Generated by Django 5.2.9 on 2026-03-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
    ]
