# Generated by Django 5.2.9 on 2026-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff_member',
        ),
        migrations.AddField(
            model_name='user',
            name='is_department_staff',
            field=models.BooleanField(default=False),
        ),
    ]
