# Generated by Django 5.2.9 on 2026-03-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='availability_status',
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
