# Generated by Django 5.2.9 on 2026-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_availability_status_user_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_department_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
    ]
