# Generated by Django 5.2.9 on 2026-03-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_is_staff_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff_member',
        ),
    ]
