# Generated by Django 5.2.9 on 2026-03-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='department',
        ),
        migrations.AddField(
            model_name='complaint',
            name='departments',
            field=models.ManyToManyField(blank=True, to='complaints.department'),
        ),
    ]
