# Generated by Django 5.2.9 on 2026-03-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_remove_complaint_department_complaint_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency (High Priority)')], default='Normal', max_length=20),
        ),
    ]
