# Generated by Django 5.2.9 on 2026-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_latitude_complaint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='authority_designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='authority_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='authority_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='authority_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='higher_authority_contact',
            field=models.TextField(blank=True, help_text='Contact info for higher authority if complaint is overdue', null=True),
        ),
    ]
