# Generated by Django 5.2.9 on 2026-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_department_authority_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='higher_authority_designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='higher_authority_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='higher_authority_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='higher_authority_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
