# Generated by Django 5.2.9 on 2026-03-18 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_department_higher_authority_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='departments',
            field=models.ManyToManyField(blank=True, to='complaints.department', verbose_name='departments'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_escalated',
            field=models.BooleanField(default=False, verbose_name='is escalated'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency (High Priority)')], default='Normal', max_length=20, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='department',
            name='authority_designation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='authority designation'),
        ),
        migrations.AlterField(
            model_name='department',
            name='authority_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='authority email'),
        ),
        migrations.AlterField(
            model_name='department',
            name='authority_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='authority name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='authority_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='authority phone'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='higher_authority_contact',
            field=models.TextField(blank=True, help_text='Contact info for higher authority if complaint is overdue', null=True, verbose_name='higher authority contact'),
        ),
        migrations.AlterField(
            model_name='department',
            name='higher_authority_designation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='higher authority designation'),
        ),
        migrations.AlterField(
            model_name='department',
            name='higher_authority_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='higher authority email'),
        ),
        migrations.AlterField(
            model_name='department',
            name='higher_authority_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='higher authority name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='higher_authority_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='higher authority phone'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint', verbose_name='complaint'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField(verbose_name='update text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='complaints.complaint', verbose_name='complaint')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
            options={
                'verbose_name': 'complaint update',
                'verbose_name_plural': 'complaint updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
