# Generated by Django 5.2.9 on 2026-03-18 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_notification_options_complaint_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Pending', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='StaffComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_updates', to='complaints.complaint', verbose_name='complaint')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_updates', to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
            options={
                'verbose_name': 'staff complaint update',
                'verbose_name_plural': 'staff complaint updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ComplaintUpdate',
        ),
    ]
