# Generated by Django 5.2.9 on 2026-03-23 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_remove_complaint_assigned_to_alter_complaint_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='assigned staff'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='staff_update',
            field=models.TextField(blank=True, null=True, verbose_name='staff update'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Pending', max_length=20, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='StaffComplaintUpdate',
        ),
    ]
