# Generated by Django 5.2.9 on 2026-03-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_assigned_staff_complaint_staff_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='staff_update',
        ),
        migrations.AddField(
            model_name='complaint',
            name='staff_remarks',
            field=models.TextField(blank=True, verbose_name='staff remarks'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Work Completed', 'Work Completed'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Escalated', 'Escalated')], default='Pending', max_length=20, verbose_name='status'),
        ),
    ]
