# Generated by Django 5.2.9 on 2026-03-27 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_remove_complaint_staff_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_staff',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='staff_remarks',
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='is assigned'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='progress_notes',
            field=models.TextField(blank=True, null=True, verbose_name='progress notes'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Escalated', 'Escalated')], default='Pending', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='full name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], default='Available', max_length=20, verbose_name='availability status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='complaints.department', verbose_name='department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
            options={
                'verbose_name': 'department staff',
                'verbose_name_plural': 'department staff',
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='complaints.departmentstaff', verbose_name='assigned to'),
        ),
    ]
