# Generated by Django 5.2.9 on 2026-03-27 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_department_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentstaff',
            name='pin',
        ),
        migrations.AddField(
            model_name='departmentstaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmentstaff', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='complaints.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
