# Generated by Django 5.2.9 on 2026-03-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_remove_departmentstaff_pin_departmentstaff_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentstaff',
            options={'ordering': ['name'], 'verbose_name': 'department staff', 'verbose_name_plural': 'department staff'},
        ),
        migrations.RemoveField(
            model_name='departmentstaff',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='staff_remarks',
            field=models.TextField(blank=True, default='', verbose_name='staff remarks'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='complaints.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
