# Generated by Django 5.2.9 on 2026-03-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0018_alter_departmentstaff_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentstaff',
            options={'verbose_name': 'department staff', 'verbose_name_plural': 'department staff'},
        ),
        migrations.RemoveField(
            model_name='departmentstaff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='departmentstaff',
            name='name',
        ),
        migrations.AddField(
            model_name='departmentstaff',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
